### ISSUE TITLE
Login UI (Flutter application)

### ISSUE THREAD

**Issue by naman1102** [naman1102/KanBan-Hacktober#5]
#### 🐞 Problem
-  Develop login ui / ux, color theme should easily changeable

#### 🎯 Goal
-  develop login ui for the application.

#### 📋 Steps to solve the problem
- Comment below about what you've started working on.
- Add, commit, push your changes.
- Submit a pull request and add this in comments - Addresses #<put issue number here>
- Ask for reviews in comments section of pull request.
- Celebrate your contribution to this project. 🎉

**Comment by mitf** [comment]
hi @naman1102 can i take this issue

**Comment by naman1102** [comment]
@mitf sure..

**Comment by mitf** [comment]
can you check my PR #10 for this issue
